# Generated by Django 4.1 on 2023-01-31 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('acontecimento_negativo', models.TextField(max_length=100, verbose_name='Acontecimento Negativo')),
                ('acontecimento_positivo', models.TextField(max_length=100, verbose_name='Acontecimento Positivo')),
                ('estado_mental', models.CharField(choices=[('P', 'PÉSSIMO'), ('R', 'RUIM'), ('B', 'BOM'), ('E', 'EXCELENTE')], max_length=2, verbose_name='Selecione o seu estado mental atual')),
                ('alerta_crises', models.CharField(choices=[('P', 'PANICO'), ('A', 'ANSIEDADE'), ('D', 'DEPRESSAO')], max_length=2, verbose_name='Selecione o seu estado de crise')),
                ('data_atual', models.DateTimeField(auto_now=True)),
                ('data_acontecimento', models.DateField(default=datetime.date(1973, 2, 11), max_length=50)),
                ('data_superacao', models.DateField(default=datetime.date(1973, 2, 11), max_length=50)),
            ],
        ),
    ]
